name: Auto-Build-Release
run-name: ${{ github.actor }} is building new release.
on: 
  push:
    #tags:
    #  - "v*.*.*"
jobs:
  do-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Initalizing Environment
        uses: actions/checkout@main
      - name: Build Factors
        id: build
        run: |
          chmod a+x ./smartdns/run_build.sh
          ./smartdns/run_build.sh && echo "status=success" >> $GITHUB_OUTPUT
      - name: Upload Artifact
        uses: actions/upload-artifact@main
        if: steps.build.outputs.status == 'success'
        with:
          name: Result Files
          path: |
            ./smartdns/outputs/cn_domains.conf
            ./smartdns/outputs/apple_china.conf
            ./smartdns/outputs/google_china.conf
      - name: Release
        uses: softprops/action-gh-release@v1
        if: steps.build.outputs.status == 'success'
        with:
          tag_name: Auto-Build
          name: Release ${{ github.ref }}
          body: Auto Build script did this.
          draft: false
          prerelease: false
          files: |
            ./smartdns/outputs/cn_domains.conf
            ./smartdns/outputs/apple_china.conf
            ./smartdns/outputs/google_china.conf
          
  
