name: Auto-Build-Release
run-name: ${{ github.actor }} is building new release.
on: [push]
jobs:
  do-builds:
    runs-on: ubuntu-latest
    steps:
      - name: Initalizing Environment
        uses: actions/checkout@v3
      - name: Build Factors
        run: |
          chmod a+x ./smartdns/run_build.sh
          ./smartdns/run_build.sh
      - name: Generate Changelog
        run: echo "# Good things have arrived" > ${{ github.workspace }}-CHANGELOG.txt
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_REPOSITORY: AzulEterno/smartdns-china-list
  
