name: Auto-Build-Release
run-name: ${{ github.actor }} is building new release.
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

  do-builds:
    runs-on: ubuntu-latest
    steps:
      - run: chmod a+x ./smartdns/run_build.sh
      - run: ./smartdns/run_build.sh
  
