name: format_smartdns
run-name: Updating format to smart dns
on: [push]
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Build
        uses: AzulEterno/smartdns-china-list@main
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          BRANCH: main
          FOLDER: .
          BUILD_SCRIPT: ./smartdns/run_build.sh
        
        
